package HelloWorldApp;


/**
* HelloWorldApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorldApp.idl
* lundi 20 octobre 2025 17 h 27 WEST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
